### ISSUE TITLE
Not handling single page application navigation errors

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/html-errors#6]
Hi, I was hoping to Print a simple custom message error into the forum and discover this extension but is not working as for see the custom error user has to refresh manually the page

https://i.postimg.cc/YCVrphM0/flarum-error-custom-broken.gif

https://discuss.flarum.org/d/10784-friendsofflarum-custom-html-error-pages/31

Flarum Beta 15

**Comment by clarkwinkelmann** [comment]
I think that's intended behavior.

This extension only handles HTTP error pages, not navigation errors inside of the Mithril single page app. So any link that Flarum routes inside of the single page app by default, like links to discussions or tags in event posts will be handled by error handling built into that particular page component and not the HTTP error page.

Links inside of comment posts are usually handled as expected since they are never routed inside of the single page app even if they open in the same tab.

**Comment by PeopleInside** [comment]
Umh so if I have a forum that need link to a private discussion that will give to the public an error I will be not able to customize in any way the error?

https://community.marcoborla.it/d/18-quando-un-dito-indica-la-luna-solo-uno-sciocco-guarda-il-dito-e-non-la-luna

As admin if I click on the split post I can see the content and is correct but visitor should see something: you don't have the permission.

So no solution for this?
this can be implemented in this extension or I should ask help in the Flarum community to see for another solution?

thanks for the help and the reply.

**Comment by clarkwinkelmann** [comment]
Ultimately Flarum will handle errors using the single page app https://github.com/flarum/core/issues/2214

When that happens, this extension will no longer be relevant. Customizing the Mithril component of the error page will be the new way, and will work for both pages accessed directly or routed internally.

That being said, if you share a link, the user should see the custom error page, since it will be accessed directly via HTTP.

There are very few situations in which Flarum will render a link to a page you can't see using single page app routing, usually the link is simply not rendered (for example, link to a deleted tag).

For this particular situation and if it's likely the "split" event post will contain link to private discussions, you could use the Flarum extension API to change that link into a normal link instead of an internal single page app navigation. Then this will always force a refresh of the browser page and will use the custom HTML error page.

I'm not sure if it makes sense to add a setting for that into the Split extension itself as killing the single page navigation isn't a real use case. Other extensions like Links have an option to select between internal and external links but the option exists because we allow user-provided links.

The best here would probably be to use a local extender or a very simple extension to extend/replace the Split event post component with one that doesn't route the link. Or fork the extension. The thing to change would be `Link` to `a` in https://github.com/FriendsOfFlarum/split/blob/master/js/src/forum/components/DiscussionSplit.js#L36

If you have a large number of connected users, they will lose the performance benefit of the internal single page app navigation. You could dynamically change between `Link` and `a` for logged in and logged out users.

**Comment by PeopleInside** [comment]
I don't like to see a blank page that still loading as error.
This is what I wanna change but seem I cannot customize that page, I will keep as is but this is not so nice for Falrum.

A blank page that still loading and a red message on left down side that is covered from my cookie banner :D
thanks anyway for replies and help!
